using System.Text;
using WellVersed.Core.Models;

namespace WellVersed.Core.Services;

/// <summary>
/// Generates a complete, compilable Verse device from a WidgetSpec.
///
/// UEFN Widget Containment Rules:
///   player_ui → canvas → canvas_slot → widget
///   overlay → overlay_slot → widget
///   stack_box → stack_box_slot → widget
///   size_box → single child widget (no slot needed)
///   text_block, color_block, texture_block, button_* → leaf (no children)
///
/// The root MUST be a CanvasPanel which maps to a Verse `canvas`.
/// Every container type dictates the slot type for its children.
/// </summary>
public static class WidgetSpecVerseGenerator
{
    public static string Generate(WidgetSpec spec)
    {
        var sb = new StringBuilder();
        var buttons = new List<WidgetNode>();
        var texts = new List<WidgetNode>();
        var images = new List<WidgetNode>();
        CollectNodes(spec.Root, buttons, texts, images);

        var className = Sanitize(spec.Name) + "_controller";

        // Header
        sb.AppendLine($"# {spec.Name} — Generated by WellVersed");
        sb.AppendLine($"# Verse controller with {buttons.Count} buttons, {texts.Count} text blocks, {images.Count} images");
        sb.AppendLine();
        sb.AppendLine("using { /Fortnite.com/Devices }");
        sb.AppendLine("using { /Fortnite.com/UI }");
        sb.AppendLine("using { /Verse.org/Simulation }");
        sb.AppendLine("using { /UnrealEngine.com/Temporary/UI }");
        sb.AppendLine("using { /UnrealEngine.com/Temporary/SpatialMath }");
        sb.AppendLine();
        sb.AppendLine($"{className} := class(creative_device):");
        sb.AppendLine();

        // Widget reference vars
        sb.AppendLine("    # === Widget References (for runtime updates) ===");
        sb.AppendLine("    var MaybeCanvas : ?canvas = false");
        sb.AppendLine("    var MaybePlayerUI : ?player_ui = false");
        foreach (var t in texts)
            sb.AppendLine($"    var {Sanitize(t.Name)} : ?text_block = false");
        foreach (var b in buttons)
        {
            var btnType = b.ButtonStyle.ToString().ToLowerInvariant();
            sb.AppendLine($"    var {Sanitize(b.Name)} : ?button_{btnType} = false");
        }
        sb.AppendLine();

        // OnBegin
        sb.AppendLine("    OnBegin<override>()<suspends>:void =");
        sb.AppendLine("        for (Player : GetPlayspace().GetPlayers()):");
        sb.AppendLine("            ShowUI(Player)");
        sb.AppendLine("        GetPlayspace().PlayerAddedEvent().Subscribe(OnPlayerAdded)");
        sb.AppendLine();
        sb.AppendLine("    OnPlayerAdded(Player : player):void =");
        sb.AppendLine("        ShowUI(Player)");
        sb.AppendLine();

        // ShowUI — creates widget instances, subscribes events, builds canvas
        sb.AppendLine("    ShowUI(Player : player):void =");
        sb.AppendLine("        if (PlayerUI := GetPlayerUI[Player]):");
        sb.AppendLine();

        // Create text block instances
        foreach (var t in texts)
        {
            var v = Sanitize(t.Name);
            sb.AppendLine($"            {v}Block := text_block{{DefaultText := StringToMessage(\"{Escape(t.Text ?? "")}\")}}");
            sb.AppendLine($"            set {v} = option{{{v}Block}}");
        }
        sb.AppendLine();

        // Create button instances + subscribe OnClick
        foreach (var b in buttons)
        {
            var v = Sanitize(b.Name);
            var btnType = $"button_{b.ButtonStyle.ToString().ToLowerInvariant()}";
            sb.AppendLine($"            {v}Btn := {btnType}{{DefaultText := StringToMessage(\"{Escape(b.Text ?? "BUTTON")}\")}}");
            sb.AppendLine($"            set {v} = option{{{v}Btn}}");
            sb.AppendLine($"            {v}Btn.OnClick().Subscribe(Handle_{v})");
        }
        sb.AppendLine();

        // Build the canvas tree — this is the critical containment hierarchy
        sb.AppendLine("            # Build the UI — valid UEFN widget containment");
        sb.AppendLine("            MyCanvas := canvas:");
        sb.AppendLine("                Slots := array:");

        // Root must be CanvasPanel → each child gets a canvas_slot
        foreach (var child in spec.Root.Children)
        {
            EmitCanvasSlot(sb, child, texts, buttons, "                    ");
        }

        sb.AppendLine();
        sb.AppendLine("            PlayerUI.AddWidget(MyCanvas)");
        sb.AppendLine("            set MaybeCanvas = option{MyCanvas}");
        sb.AppendLine("            set MaybePlayerUI = option{PlayerUI}");
        sb.AppendLine();

        // HideUI
        sb.AppendLine("    HideUI():void =");
        sb.AppendLine("        if (PUI := MaybePlayerUI?, Widget := MaybeCanvas?):");
        sb.AppendLine("            PUI.RemoveWidget(Widget)");
        sb.AppendLine("            set MaybeCanvas = false");
        sb.AppendLine();

        // Button handlers
        sb.AppendLine("    # === Button Click Handlers ===");
        foreach (var b in buttons)
        {
            var v = Sanitize(b.Name);
            sb.AppendLine($"    Handle_{v}(Message : widget_message):void =");
            sb.AppendLine($"        # TODO: Add your game logic for \"{b.Name}\"");
            sb.AppendLine($"        Print(\"[{spec.Name}] {b.Name} clicked\")");
            sb.AppendLine();
        }

        // Text update helpers
        sb.AppendLine("    # === Text Update Helpers ===");
        foreach (var t in texts)
        {
            var v = Sanitize(t.Name);
            sb.AppendLine($"    Set{v}(NewText : string):void =");
            sb.AppendLine($"        if (Block := {v}?):  Block.SetText(StringToMessage(NewText))");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emit a canvas_slot wrapping a child widget.
    /// Canvas children always need canvas_slot with Anchors.
    /// </summary>
    private static void EmitCanvasSlot(StringBuilder sb, WidgetNode node,
        List<WidgetNode> texts, List<WidgetNode> buttons, string indent)
    {
        sb.AppendLine($"{indent}canvas_slot:");

        var (anchorMin, anchorMax, align) = GetAnchors(node.Anchor);
        sb.AppendLine($"{indent}    Anchors := anchors{{Minimum := {anchorMin}, Maximum := {anchorMax}}}");
        if (align != null)
            sb.AppendLine($"{indent}    {align}");

        // Offsets if specified
        if (node.OffsetLeft != 0 || node.OffsetTop != 0 || node.OffsetRight != 0 || node.OffsetBottom != 0)
            sb.AppendLine($"{indent}    Offsets := margin{{Left := {node.OffsetLeft:F1}, Top := {node.OffsetTop:F1}, Right := {node.OffsetRight:F1}, Bottom := {node.OffsetBottom:F1}}}");

        if (node.AutoSize)
            sb.AppendLine($"{indent}    SizeToContent := true");

        sb.Append($"{indent}    Widget := ");
        EmitWidget(sb, node, texts, buttons, indent + "    ");
    }

    /// <summary>
    /// Emit a widget expression. Handles containers (with proper slot types) and leaves.
    /// </summary>
    private static void EmitWidget(StringBuilder sb, WidgetNode node,
        List<WidgetNode> texts, List<WidgetNode> buttons, string indent)
    {
        switch (node.Type)
        {
            case WidgetType.TextBlock:
                sb.AppendLine($"{Sanitize(node.Name)}Block");
                break;

            case WidgetType.ButtonLoud:
            case WidgetType.ButtonQuiet:
            case WidgetType.ButtonRegular:
                sb.AppendLine($"{Sanitize(node.Name)}Btn");
                break;

            case WidgetType.Image when node.TintColor != null:
                var (r, g, b, a) = ParseHex(node.TintColor);
                sb.AppendLine($"color_block{{DefaultColor := color{{R := {r:F2}, G := {g:F2}, B := {b:F2}, A := {a:F2}}}}}");
                break;

            case WidgetType.Image:
                // Texture block or placeholder
                if (node.TexturePath != null)
                    sb.AppendLine($"texture_block{{DefaultImage := {Sanitize(node.TexturePath)}}}");
                else
                    sb.AppendLine($"color_block{{DefaultColor := NamedColors.Gray}} # placeholder for {node.Name}");
                break;

            case WidgetType.Overlay:
                sb.AppendLine("overlay:");
                sb.AppendLine($"{indent}    Slots := array:");
                foreach (var child in node.Children)
                {
                    sb.AppendLine($"{indent}        overlay_slot:");
                    sb.Append($"{indent}            Widget := ");
                    EmitWidget(sb, child, texts, buttons, indent + "            ");
                }
                break;

            case WidgetType.StackBox:
                var orient = node.Orientation == Orientation.Horizontal ? "orientation.Horizontal" : "orientation.Vertical";
                sb.AppendLine("stack_box:");
                sb.AppendLine($"{indent}    Orientation := {orient}");
                sb.AppendLine($"{indent}    Slots := array:");
                foreach (var child in node.Children)
                {
                    sb.AppendLine($"{indent}        stack_box_slot:");
                    sb.Append($"{indent}            Widget := ");
                    EmitWidget(sb, child, texts, buttons, indent + "            ");
                }
                break;

            case WidgetType.SizeBox:
                sb.AppendLine("size_box:");
                if (node.MinWidth > 0)
                    sb.AppendLine($"{indent}    WidthOverride := {node.MinWidth}.0");
                if (node.MinHeight > 0)
                    sb.AppendLine($"{indent}    HeightOverride := {node.MinHeight}.0");
                if (node.Children.Count > 0)
                {
                    sb.Append($"{indent}    Slot := ");
                    EmitWidget(sb, node.Children[0], texts, buttons, indent + "    ");
                }
                break;

            case WidgetType.CanvasPanel:
                // Nested canvas (rare but valid)
                sb.AppendLine("canvas:");
                sb.AppendLine($"{indent}    Slots := array:");
                foreach (var child in node.Children)
                    EmitCanvasSlot(sb, child, texts, buttons, indent + "        ");
                break;

            default:
                sb.AppendLine($"color_block{{}} # unknown type {node.Type}");
                break;
        }
    }

    private static (string min, string max, string? align) GetAnchors(AnchorPreset preset) => preset switch
    {
        AnchorPreset.TopLeft => ("vector2{X := 0.0, Y := 0.0}", "vector2{X := 0.0, Y := 0.0}", null),
        AnchorPreset.TopCenter => ("vector2{X := 0.5, Y := 0.0}", "vector2{X := 0.5, Y := 0.0}", "Alignment := vector2{X := 0.5, Y := 0.0}"),
        AnchorPreset.TopRight => ("vector2{X := 1.0, Y := 0.0}", "vector2{X := 1.0, Y := 0.0}", "Alignment := vector2{X := 1.0, Y := 0.0}"),
        AnchorPreset.CenterLeft => ("vector2{X := 0.0, Y := 0.5}", "vector2{X := 0.0, Y := 0.5}", "Alignment := vector2{X := 0.0, Y := 0.5}"),
        AnchorPreset.Center => ("vector2{X := 0.5, Y := 0.5}", "vector2{X := 0.5, Y := 0.5}", "Alignment := vector2{X := 0.5, Y := 0.5}"),
        AnchorPreset.CenterRight => ("vector2{X := 1.0, Y := 0.5}", "vector2{X := 1.0, Y := 0.5}", "Alignment := vector2{X := 1.0, Y := 0.5}"),
        AnchorPreset.BottomLeft => ("vector2{X := 0.0, Y := 1.0}", "vector2{X := 0.0, Y := 1.0}", "Alignment := vector2{X := 0.0, Y := 1.0}"),
        AnchorPreset.BottomCenter => ("vector2{X := 0.5, Y := 1.0}", "vector2{X := 0.5, Y := 1.0}", "Alignment := vector2{X := 0.5, Y := 1.0}"),
        AnchorPreset.BottomRight => ("vector2{X := 1.0, Y := 1.0}", "vector2{X := 1.0, Y := 1.0}", "Alignment := vector2{X := 1.0, Y := 1.0}"),
        AnchorPreset.FullScreen => ("vector2{X := 0.0, Y := 0.0}", "vector2{X := 1.0, Y := 1.0}", null),
        AnchorPreset.TopStretch => ("vector2{X := 0.0, Y := 0.0}", "vector2{X := 1.0, Y := 0.0}", null),
        AnchorPreset.BottomStretch => ("vector2{X := 0.0, Y := 1.0}", "vector2{X := 1.0, Y := 1.0}", null),
        _ => ("vector2{X := 0.0, Y := 0.0}", "vector2{X := 0.0, Y := 0.0}", null)
    };

    private static void CollectNodes(WidgetNode node,
        List<WidgetNode> buttons, List<WidgetNode> texts, List<WidgetNode> images)
    {
        switch (node.Type)
        {
            case WidgetType.ButtonLoud:
            case WidgetType.ButtonQuiet:
            case WidgetType.ButtonRegular:
                buttons.Add(node);
                break;
            case WidgetType.TextBlock:
                texts.Add(node);
                break;
            case WidgetType.Image:
                images.Add(node);
                break;
        }
        foreach (var child in node.Children)
            CollectNodes(child, buttons, texts, images);
    }

    private static string Sanitize(string name) =>
        name.Replace(" ", "_").Replace("-", "_").Replace(".", "_").Replace("/", "_");

    private static string Escape(string s) =>
        s.Replace("\"", "\\\"");

    private static (float r, float g, float b, float a) ParseHex(string hex)
    {
        hex = hex.TrimStart('#');
        if (hex.Length >= 6)
            return (
                int.Parse(hex[0..2], System.Globalization.NumberStyles.HexNumber) / 255f,
                int.Parse(hex[2..4], System.Globalization.NumberStyles.HexNumber) / 255f,
                int.Parse(hex[4..6], System.Globalization.NumberStyles.HexNumber) / 255f,
                hex.Length >= 8 ? int.Parse(hex[6..8], System.Globalization.NumberStyles.HexNumber) / 255f : 1f
            );
        return (1, 1, 1, 1);
    }
}
