"""Device proxy generation -- generate Python proxy classes from placed devices.

Inspects devices in the level, reads their class hierarchy and properties,
queries digest schema if available, and generates Python proxy classes with
property accessors, method stubs, and event names. Proxies are written to
Saved/WellVersed/proxies/ so Claude can understand device APIs without docs.
"""

from __future__ import annotations

import json
import os
import re
import time
from pathlib import Path

from ..listener import register_command
from ..safety import safe_transaction

try:
    import unreal
except ImportError:
    unreal = None


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _proxies_dir() -> Path:
    """Return the proxies directory, creating it if necessary."""
    project_dir = Path(unreal.Paths.project_dir())
    proxies_path = project_dir / "Saved" / "WellVersed" / "proxies"
    proxies_path.mkdir(parents=True, exist_ok=True)
    return proxies_path


def _find_actor_by_name(name: str):
    """Find a level actor by its name or label."""
    for actor in unreal.EditorLevelLibrary.get_all_level_actors():
        if actor.get_name() == name or actor.get_actor_label() == name:
            return actor
    return None


def _get_property_info(actor) -> list[dict]:
    """Extract all editable property metadata from an actor."""
    properties = []
    try:
        for prop_name in actor.get_class().get_editor_property_names():
            prop_str = str(prop_name)
            try:
                val = actor.get_editor_property(prop_str)
                type_name = type(val).__name__
                properties.append({
                    "name": prop_str,
                    "type": type_name,
                    "default_value": _safe_repr(val),
                })
            except Exception:
                properties.append({
                    "name": prop_str,
                    "type": "unknown",
                    "default_value": None,
                })
    except Exception:
        pass
    return properties


def _safe_repr(val) -> str:
    """Get a safe string representation of a value."""
    try:
        if val is None:
            return "None"
        if isinstance(val, (bool, int, float, str)):
            return repr(val)
        if hasattr(val, 'x') and hasattr(val, 'y') and hasattr(val, 'z'):
            return f"Vector({val.x}, {val.y}, {val.z})"
        if hasattr(val, 'pitch') and hasattr(val, 'yaw'):
            return f"Rotator({val.pitch}, {val.yaw}, {val.roll})"
        return str(val)
    except Exception:
        return "<?>"


def _get_class_hierarchy(actor) -> list[str]:
    """Walk the class hierarchy of an actor."""
    hierarchy = []
    cls = actor.get_class()
    while cls is not None:
        hierarchy.append(cls.get_name())
        try:
            cls = cls.get_super_class()
        except Exception:
            break
    return hierarchy


def _detect_events(properties: list[dict]) -> list[str]:
    """Detect event/delegate properties by naming patterns."""
    event_patterns = [
        "on_", "event_", "delegate_", "_event", "_delegate",
        "on_begin", "on_end", "on_trigger", "on_activated",
        "on_completed", "on_changed", "on_damaged", "on_eliminated",
    ]
    events = []
    for prop in properties:
        name_lower = prop["name"].lower()
        if any(pattern in name_lower for pattern in event_patterns):
            events.append(prop["name"])
        elif "multicast" in prop.get("type", "").lower():
            events.append(prop["name"])
        elif "delegate" in prop.get("type", "").lower():
            events.append(prop["name"])
    return events


def _python_type(type_name: str) -> str:
    """Map Unreal type names to Python type hints."""
    mapping = {
        "bool": "bool",
        "int": "int",
        "float": "float",
        "str": "str",
        "Name": "str",
        "Text": "str",
        "Vector": "unreal.Vector",
        "Rotator": "unreal.Rotator",
        "LinearColor": "unreal.LinearColor",
        "Color": "unreal.Color",
        "Transform": "unreal.Transform",
    }
    return mapping.get(type_name, "Any")


def _generate_proxy_code(
    class_name: str,
    class_path: str,
    hierarchy: list[str],
    properties: list[dict],
    events: list[str],
) -> str:
    """Generate Python proxy class source code."""
    lines = [
        f'"""Auto-generated proxy for {class_name}.',
        f"",
        f"Class path: {class_path}",
        f"Hierarchy: {' -> '.join(hierarchy)}",
        f'Generated by WellVersed bridge at {time.strftime("%Y-%m-%d %H:%M:%S")}',
        f'"""',
        f"",
        f"from typing import Any",
        f"",
        f"",
        f"class {class_name}Proxy:",
        f'    """Proxy for {class_name} device.',
        f"",
        f"    Provides typed property accessors and event names for",
        f"    interacting with {class_name} actors in the level.",
        f'    """',
        f"",
        f'    CLASS_PATH = "{class_path}"',
        f"    HIERARCHY = {hierarchy!r}",
        f"",
    ]

    # Event constants
    if events:
        lines.append("    # Events / Delegates")
        for event in events:
            const_name = event.upper()
            lines.append(f'    {const_name} = "{event}"')
        lines.append("")

    # Init
    lines.append("    def __init__(self, actor_name: str):")
    lines.append('        """Bind to an existing actor by name."""')
    lines.append("        self.actor_name = actor_name")
    lines.append("")

    # Property accessors
    if properties:
        lines.append("    # --- Property Accessors ---")
        lines.append("")

    for prop in properties:
        prop_name = prop["name"]
        py_type = _python_type(prop["type"])
        safe_method_name = re.sub(r"[^a-zA-Z0-9_]", "_", prop_name)

        lines.append(f"    @property")
        lines.append(f"    def {safe_method_name}(self) -> {py_type}:")
        lines.append(f'        """Read {prop_name} (type: {prop["type"]}, default: {prop["default_value"]})."""')
        lines.append(f"        # Use: bridge.get_actor_properties(self.actor_name, ['{prop_name}'])")
        lines.append(f"        ...")
        lines.append(f"")
        lines.append(f"    @{safe_method_name}.setter")
        lines.append(f"    def {safe_method_name}(self, value: {py_type}):")
        lines.append(f'        """Set {prop_name}."""')
        lines.append(f"        # Use: bridge.set_actor_properties(self.actor_name, {{'{prop_name}': value}})")
        lines.append(f"        ...")
        lines.append(f"")

    # Summary method
    lines.append("    def get_all_properties(self) -> dict:")
    lines.append('        """Return all known property names and types."""')
    lines.append("        return {")
    for prop in properties:
        lines.append(f'            "{prop["name"]}": "{prop["type"]}",')
    lines.append("        }")
    lines.append("")

    # Events list
    lines.append("    def get_events(self) -> list[str]:")
    lines.append('        """Return all event/delegate names."""')
    lines.append(f"        return {events!r}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

@register_command("generate_device_proxy")
def generate_device_proxy(params: dict) -> dict:
    """Generate a Python proxy class for a placed device.

    Inspects the device actor, reads its class hierarchy and properties,
    detects events/delegates, and writes a proxy .py file to
    Saved/WellVersed/proxies/.

    Parameters
    ----------
    params.actor_name : str
        Name or label of the device actor in the level.
    """
    if not unreal:
        return {"status": "error", "error": "unreal module not available"}

    actor_name = params["actor_name"]
    actor = _find_actor_by_name(actor_name)
    if actor is None:
        return {"status": "error", "error": f"Actor not found: {actor_name}"}

    class_name = actor.get_class().get_name()
    class_path = actor.get_class().get_path_name()
    hierarchy = _get_class_hierarchy(actor)
    properties = _get_property_info(actor)
    events = _detect_events(properties)

    proxy_code = _generate_proxy_code(
        class_name, class_path, hierarchy, properties, events
    )

    # Write proxy file
    safe_name = re.sub(r"[^a-zA-Z0-9_]", "_", class_name)
    file_path = _proxies_dir() / f"{safe_name}_proxy.py"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(proxy_code)

    # Also write a JSON metadata file
    meta_path = _proxies_dir() / f"{safe_name}_meta.json"
    meta = {
        "class_name": class_name,
        "class_path": class_path,
        "hierarchy": hierarchy,
        "property_count": len(properties),
        "event_count": len(events),
        "events": events,
        "properties": properties,
        "generated_at": time.time(),
    }
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    return {
        "status": "ok",
        "data": {
            "class_name": class_name,
            "proxy_file": str(file_path),
            "meta_file": str(meta_path),
            "property_count": len(properties),
            "event_count": len(events),
            "events": events,
        },
    }


@register_command("generate_all_proxies")
def generate_all_proxies(params: dict) -> dict:
    """Generate proxy classes for every device in the level.

    Scans all actors, identifies those that look like Creative devices
    (based on class name heuristics), and generates a proxy for each
    unique device class.

    Parameters
    ----------
    params.class_filter : str, optional
        Only generate proxies for classes containing this substring.
    """
    if not unreal:
        return {"status": "error", "error": "unreal module not available"}

    class_filter = params.get("class_filter", "").lower()
    all_actors = unreal.EditorLevelLibrary.get_all_level_actors()

    # Deduplicate by class path
    seen_classes: dict[str, object] = {}
    for actor in all_actors:
        class_name = actor.get_class().get_name()
        class_path = actor.get_class().get_path_name()

        # Heuristic: is this a device?
        name_lower = class_name.lower()
        is_device = any(kw in name_lower for kw in [
            "device", "creative", "manager", "spawner", "trigger",
            "controller", "tracker", "zone", "barrier", "teleporter",
            "vending", "timer", "scoreboard", "button", "switch",
        ])

        if not is_device:
            continue

        if class_filter and class_filter not in name_lower:
            continue

        if class_path not in seen_classes:
            seen_classes[class_path] = actor

    # Generate proxy for each unique class
    generated = []
    errors = []

    for class_path, actor in seen_classes.items():
        try:
            result = generate_device_proxy({"actor_name": actor.get_name()})
            if result.get("status") == "ok":
                generated.append(result["data"])
            else:
                errors.append({
                    "class": actor.get_class().get_name(),
                    "error": result.get("error", "Unknown error"),
                })
        except Exception as exc:
            errors.append({
                "class": actor.get_class().get_name(),
                "error": str(exc),
            })

    # Write an index file
    index_path = _proxies_dir() / "_index.json"
    index_data = {
        "generated_at": time.time(),
        "proxy_count": len(generated),
        "proxies": [
            {"class": g["class_name"], "file": g["proxy_file"]}
            for g in generated
        ],
    }
    with open(index_path, "w", encoding="utf-8") as f:
        json.dump(index_data, f, indent=2)

    return {
        "status": "ok",
        "data": {
            "generated": len(generated),
            "errors": len(errors),
            "proxies": generated,
            "error_details": errors[:20],
            "index_file": str(index_path),
        },
    }
