import type { DeviceRecipe } from './recipes'

/**
 * Built-in device recipe templates.
 * These are common multi-device patterns that UEFN creators use frequently.
 */
export const BUILTIN_RECIPES: DeviceRecipe[] = [
  {
    $schema: 'device-recipe-v1',
    id: 'builtin-capture-point',
    name: 'Capture Point',
    description: 'A zone-based capture point with scoring, timer, and HUD feedback. Players enter the trigger zone to start capturing.',
    category: 'gameplay',
    tags: ['Trigger', 'Score', 'Timer', 'HUD', 'Zone Control'],
    author: 'WellVersed',
    createdAt: '2026-01-01T00:00:00Z',
    devices: [
      {
        role: 'capture_trigger',
        deviceClass: 'BP_TriggerDevice_C',
        displayName: 'Capture Zone Trigger',
        offset: { x: 0, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 3, y: 3, z: 2 },
        properties: [
          { name: 'TriggerShape', value: 'Box', type: 'EnumProperty' },
          { name: 'bVisibleInGame', value: 'True', type: 'BoolProperty' },
        ],
      },
      {
        role: 'score_manager',
        deviceClass: 'BP_ScoreManagerDevice_C',
        displayName: 'Capture Score Manager',
        offset: { x: 200, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [
          { name: 'ScoreToAward', value: '1', type: 'IntProperty' },
        ],
      },
      {
        role: 'capture_timer',
        deviceClass: 'BP_TimerDevice_C',
        displayName: 'Capture Timer',
        offset: { x: 200, y: 200, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [
          { name: 'Duration', value: '5', type: 'FloatProperty' },
        ],
      },
      {
        role: 'capture_hud',
        deviceClass: 'BP_HUDMessageDevice_C',
        displayName: 'Capturing... Message',
        offset: { x: 400, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [
          { name: 'MessageText', value: 'Capturing Point...', type: 'StrProperty' },
        ],
      },
    ],
    wiring: [
      { sourceRole: 'capture_trigger', outputEvent: 'OnTriggered', targetRole: 'capture_timer', inputAction: 'Start' },
      { sourceRole: 'capture_trigger', outputEvent: 'OnTriggered', targetRole: 'capture_hud', inputAction: 'Show' },
      { sourceRole: 'capture_timer', outputEvent: 'OnCompleted', targetRole: 'score_manager', inputAction: 'Activate' },
      { sourceRole: 'capture_trigger', outputEvent: 'OnUntriggered', targetRole: 'capture_timer', inputAction: 'Reset' },
      { sourceRole: 'capture_trigger', outputEvent: 'OnUntriggered', targetRole: 'capture_hud', inputAction: 'Hide' },
    ],
  },
  {
    $schema: 'device-recipe-v1',
    id: 'builtin-item-shop',
    name: 'Item Shop',
    description: 'A vending machine with item granter and visual effect feedback. Players interact to receive items.',
    category: 'economy',
    tags: ['Vending Machine', 'Item Granter', 'Shop', 'Economy'],
    author: 'WellVersed',
    createdAt: '2026-01-01T00:00:00Z',
    devices: [
      {
        role: 'vending_machine',
        deviceClass: 'BP_VendingMachineDevice_C',
        displayName: 'Item Vendor',
        offset: { x: 0, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'item_granter',
        deviceClass: 'BP_ItemGranterDevice_C',
        displayName: 'Purchased Item Granter',
        offset: { x: 200, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'purchase_effect',
        deviceClass: 'BP_VisualEffectDevice_C',
        displayName: 'Purchase VFX',
        offset: { x: 0, y: 0, z: 100 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'purchase_message',
        deviceClass: 'BP_HUDMessageDevice_C',
        displayName: 'Purchase Confirmation',
        offset: { x: 200, y: 200, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [
          { name: 'MessageText', value: 'Item Purchased!', type: 'StrProperty' },
        ],
      },
    ],
    wiring: [
      { sourceRole: 'vending_machine', outputEvent: 'OnItemPurchased', targetRole: 'item_granter', inputAction: 'GrantItem' },
      { sourceRole: 'vending_machine', outputEvent: 'OnItemPurchased', targetRole: 'purchase_effect', inputAction: 'Play' },
      { sourceRole: 'vending_machine', outputEvent: 'OnItemPurchased', targetRole: 'purchase_message', inputAction: 'Show' },
    ],
  },
  {
    $schema: 'device-recipe-v1',
    id: 'builtin-spawn-area',
    name: 'Team Spawn Area',
    description: 'A cluster of player spawners with barrier protection and a spawn timer. Standard team spawn setup.',
    category: 'spawning',
    tags: ['Player Spawner', 'Barrier', 'Team', 'Spawn Protection'],
    author: 'WellVersed',
    createdAt: '2026-01-01T00:00:00Z',
    devices: [
      {
        role: 'spawn_1',
        deviceClass: 'BP_PlayerSpawnDevice_C',
        displayName: 'Spawn Point 1',
        offset: { x: -200, y: -200, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'spawn_2',
        deviceClass: 'BP_PlayerSpawnDevice_C',
        displayName: 'Spawn Point 2',
        offset: { x: 200, y: -200, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'spawn_3',
        deviceClass: 'BP_PlayerSpawnDevice_C',
        displayName: 'Spawn Point 3',
        offset: { x: -200, y: 200, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'spawn_4',
        deviceClass: 'BP_PlayerSpawnDevice_C',
        displayName: 'Spawn Point 4',
        offset: { x: 200, y: 200, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'spawn_barrier',
        deviceClass: 'BP_BarrierDevice_C',
        displayName: 'Spawn Protection Barrier',
        offset: { x: 0, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 5, y: 5, z: 3 },
        properties: [
          { name: 'bEnabled', value: 'True', type: 'BoolProperty' },
        ],
      },
      {
        role: 'protection_timer',
        deviceClass: 'BP_TimerDevice_C',
        displayName: 'Spawn Protection Timer',
        offset: { x: 400, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [
          { name: 'Duration', value: '10', type: 'FloatProperty' },
        ],
      },
    ],
    wiring: [
      { sourceRole: 'protection_timer', outputEvent: 'OnCompleted', targetRole: 'spawn_barrier', inputAction: 'Disable' },
    ],
  },
  {
    $schema: 'device-recipe-v1',
    id: 'builtin-elimination-tracker',
    name: 'Elimination Tracker',
    description: 'Tracks eliminations, shows kill count on HUD, and triggers events at kill milestones.',
    category: 'combat',
    tags: ['Elimination', 'Score', 'HUD', 'Tracker', 'Combat'],
    author: 'WellVersed',
    createdAt: '2026-01-01T00:00:00Z',
    devices: [
      {
        role: 'elim_manager',
        deviceClass: 'BP_EliminationManagerDevice_C',
        displayName: 'Elimination Manager',
        offset: { x: 0, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [],
      },
      {
        role: 'kill_score',
        deviceClass: 'BP_ScoreManagerDevice_C',
        displayName: 'Kill Score Tracker',
        offset: { x: 200, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [
          { name: 'ScoreToAward', value: '1', type: 'IntProperty' },
        ],
      },
      {
        role: 'kill_message',
        deviceClass: 'BP_HUDMessageDevice_C',
        displayName: 'Elimination Notification',
        offset: { x: 400, y: 0, z: 0 },
        rotation: { pitch: 0, yaw: 0, roll: 0 },
        scale: { x: 1, y: 1, z: 1 },
        properties: [
          { name: 'MessageText', value: 'Eliminated!', type: 'StrProperty' },
        ],
      },
    ],
    wiring: [
      { sourceRole: 'elim_manager', outputEvent: 'OnElimination', targetRole: 'kill_score', inputAction: 'Activate' },
      { sourceRole: 'elim_manager', outputEvent: 'OnElimination', targetRole: 'kill_message', inputAction: 'Show' },
    ],
  },
]
